### ISSUE TITLE
Incompatible with Equipment and Quick Slots

### ISSUE THREAD

**Issue by Ramshackles** [xiaoxiao921/Lead#1]
It seems the 2 mods are not compatible - not sure where the problem lies.

https://valheim.thunderstore.io/package/RandyKnapp/EquipmentAndQuickSlots/

**Comment by xiaoxiao921** [comment]
Can't replicate 
![image](https://user-images.githubusercontent.com/837334/109882642-7ecab400-7c7a-11eb-9d7e-51916f4ebdda.png)

**Comment by Ramshackles** [comment]
Odd, it might be with something else I have - I'll try to narrow it down.

I see it actually happends when enabling ValheimLib, not really Lead, but since Lead depends on it I noticed it.

`[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
CustomSlotItemLib.CustomSlotManager.IsCustomSlotItem (ItemDrop+ItemData item) (at <400d054719ed43f2a67012754fb274bf>:0)
CustomSlotItemLib.Patches.IsItemEquipedPostfix (System.Boolean& __result, Humanoid& __instance, ItemDrop+ItemData item) (at <400d054719ed43f2a67012754fb274bf>:0)
(wrapper dynamic-method) Humanoid.DMD<Humanoid::IsItemEquiped>(Humanoid,ItemDrop/ItemData)
(wrapper dynamic-method) Humanoid.DMD<Humanoid::EquipItem>(Humanoid,ItemDrop/ItemData,bool)
Player.EquipIventoryItems () (at <f48d6a22696245bf8d820aad6afa4fdb>:0)
(wrapper dynamic-method) Player.DMD<Player::Load>(Player,ZPackage)
PlayerProfile.LoadPlayerData (Player player) (at <f48d6a22696245bf8d820aad6afa4fdb>:0)
FejdStartup.SetupCharacterPreview (PlayerProfile profile) (at <f48d6a22696245bf8d820aad6afa4fdb>:0)
(wrapper dynamic-method) FejdStartup.DMD<FejdStartup::UpdateCharacterList>(FejdStartup)
FejdStartup.SetSelectedProfile (System.String filename) (at <f48d6a22696245bf8d820aad6afa4fdb>:0)
(wrapper dynamic-method) FejdStartup.DMD<FejdStartup::Start>(FejdStartup)`

This is from bepinex console when the main menu shows, character is naked :)

**Comment by Ramshackles** [comment]
Alright something must be wrong with my setup, using r2mm and having only BepInExPack_Valheim 5.4.800, ValheimLib and HookGenPatcher enabled it still errors;

`[Message:   BepInEx] BepInEx 5.4.8.0 - valheim
[Info   :   BepInEx] Running under Unity v2019.4.20.7197120
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.MonoMod.HookGenPatcher 1.1.0.0]
[Info   :   BepInEx] 2 patcher plugins loaded
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [Display BepInEx Info In-Game 1.0.0]
[Info   :  HarmonyX] ### Harmony id=harmony-auto-667f4c24-fde0-4f39-a768-84daa0833262, version=2.3.2.0, location=C:\Users\xxxxx\AppData\Roaming\r2modmanPlus-local\Valheim\profiles\Default\BepInEx\core\0Harmony.dll, env/clr=4.0.30319.42000, platform=Win32NT
### Started from static void HarmonyLib.Tools.Logger::Log(HarmonyLib.Tools.Logger+LogChannel channel, System.Func<string> message), location C:\Users\xxxxx\AppData\Roaming\r2modmanPlus-local\Valheim\profiles\Default\BepInEx\core\0Harmony.dll
### At 2021-03-04 10.10.29
[Info   :  HarmonyX] Patching void FejdStartup::Start() with 0 prefixes, 1 postfixes, 0 transpilers, 0 finalizers
1 postfixes:
* static void Valheim.DisplayBepInExInfo.DisplayInfoPlugin::OnFejdStartup(FejdStartup __instance)

[Info   :  HarmonyX] Running ILHook manipulator on void FejdStartup::Start()
[Info   :  HarmonyX] Writing postfixes
[Info   :  HarmonyX] Patching static void ZNet::SetServer(bool server, bool openServer, bool publicServer, string serverName, string password, World world) with 0 prefixes, 1 postfixes, 0 transpilers, 0 finalizers
1 postfixes:
* static void Valheim.DisplayBepInExInfo.DisplayInfoPlugin::OnServerStart(string serverName)

[Info   :  HarmonyX] Running ILHook manipulator on static void ZNet::SetServer(bool server, bool openServer, bool publicServer, string serverName, string password, World world)
[Info   :  HarmonyX] Writing postfixes
[Info   :   BepInEx] Loading [ValheimLib 0.0.4]
[Message:   BepInEx] Chainloader startup complete
[Info   : Unity Log] 03/04/2021 22:10:30: Starting to load scene:start

[Warning: Unity Log] Only custom filters can be played. Please add a custom filter or an audioclip to the audiosource (Amb_MainMenu).
[Info   : Unity Log] 03/04/2021 22:10:39: Initializing world generator seed: ( 0 )   menu:True  worldgen version:1

[Info   : Unity Log] 03/04/2021 22:10:39: Using mountain distance: 1000

[Info   : Unity Log] 03/04/2021 22:10:39: Render threading mode:MultiThreaded

[Info   : Unity Log] 03/04/2021 22:10:39: Using environment steamid 892970

[Info   : Unity Log] 03/04/2021 22:10:39: Using steam APPID:892970

Setting breakpad minidump AppID = 892970
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561197967206198 [API loaded no]
[Info   : Unity Log] 03/04/2021 22:10:39: Authentication:k_ESteamNetworkingAvailability_Attempting

[Info   : Unity Log] 03/04/2021 22:10:39: Steam initialized, persona:Ramsy

[Warning: Unity Log] 03/04/2021 22:10:39: Missing audio clip in music respawn

[Info   : Unity Log] 03/04/2021 22:10:39: Checking for installed DLCs

[Info   : Unity Log] 03/04/2021 22:10:39: DLC:beta installed:False

[Info   : Unity Log] 03/04/2021 22:10:40: Loaded localization English

[Info   : Unity Log] 03/04/2021 22:10:40: Loaded localization English

[Info   : Unity Log] 03/04/2021 22:10:40: ARG 0 D:\Spil\Steam\steamapps\common\Valheim\valheim.exe

[Info   : Unity Log] 03/04/2021 22:10:40: ARG 1 --doorstop-enable

[Info   : Unity Log] 03/04/2021 22:10:40: ARG 2 true

[Info   : Unity Log] 03/04/2021 22:10:40: ARG 3 --doorstop-target

[Info   : Unity Log] 03/04/2021 22:10:40: ARG 4 C:\xxxxx\claus\AppData\Roaming\r2modmanPlus-local\Valheim\profiles\Default\BepInEx\core\BepInEx.Preloader.dll

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Humanoid.SetupVisEquipment (VisEquipment visEq, System.Boolean isRagdoll) (at <f48d6a22696245bf8d820aad6afa4fdb>:0)
Player.SetupVisEquipment (VisEquipment visEq, System.Boolean isRagdoll) (at <f48d6a22696245bf8d820aad6afa4fdb>:0)
Humanoid.SetupEquipment () (at <f48d6a22696245bf8d820aad6afa4fdb>:0)
Humanoid.EquipItem (ItemDrop+ItemData item, System.Boolean triggerEquipEffects) (at <f48d6a22696245bf8d820aad6afa4fdb>:0)
Player.EquipIventoryItems () (at <f48d6a22696245bf8d820aad6afa4fdb>:0)
Player.Load (ZPackage pkg) (at <f48d6a22696245bf8d820aad6afa4fdb>:0)
PlayerProfile.LoadPlayerData (Player player) (at <f48d6a22696245bf8d820aad6afa4fdb>:0)
FejdStartup.SetupCharacterPreview (PlayerProfile profile) (at <f48d6a22696245bf8d820aad6afa4fdb>:0)
FejdStartup.UpdateCharacterList () (at <f48d6a22696245bf8d820aad6afa4fdb>:0)
FejdStartup.SetSelectedProfile (System.String filename) (at <f48d6a22696245bf8d820aad6afa4fdb>:0)
(wrapper dynamic-method) FejdStartup.DMD<FejdStartup::Start>(FejdStartup)

[Info   : Unity Log] 03/04/2021 22:10:43: UI Group status changed Menu = True`

**Comment by xiaoxiao921** [comment]
> Odd, it might be with something else I have - I'll try to narrow it down.
> 
> I see it actually happends when enabling ValheimLib, not really Lead, but since Lead depends on it I noticed it.
> 
> `[Error : Unity Log] NullReferenceException: Object reference not set to an instance of an object Stack trace: CustomSlotItemLib.CustomSlotManager.IsCustomSlotItem (ItemDrop+ItemData item) (at <400d054719ed43f2a67012754fb274bf>:0) CustomSlotItemLib.Patches.IsItemEquipedPostfix (System.Boolean& __result, Humanoid& __instance, ItemDrop+ItemData item) (at <400d054719ed43f2a67012754fb274bf>:0) (wrapper dynamic-method) Humanoid.DMD<Humanoid::IsItemEquiped>(Humanoid,ItemDrop/ItemData) (wrapper dynamic-method) Humanoid.DMD<Humanoid::EquipItem>(Humanoid,ItemDrop/ItemData,bool) Player.EquipIventoryItems () (at <f48d6a22696245bf8d820aad6afa4fdb>:0) (wrapper dynamic-method) Player.DMD<Player::Load>(Player,ZPackage) PlayerProfile.LoadPlayerData (Player player) (at <f48d6a22696245bf8d820aad6afa4fdb>:0) FejdStartup.SetupCharacterPreview (PlayerProfile profile) (at <f48d6a22696245bf8d820aad6afa4fdb>:0) (wrapper dynamic-method) FejdStartup.DMD<FejdStartup::UpdateCharacterList>(FejdStartup) FejdStartup.SetSelectedProfile (System.String filename) (at <f48d6a22696245bf8d820aad6afa4fdb>:0) (wrapper dynamic-method) FejdStartup.DMD<FejdStartup::Start>(FejdStartup)`
> 
> This is from bepinex console when the main menu shows, character is naked :)

This is CustomSlotItemLib erroring (not a mod from me)

And in that last log I can't see any error, the SetupVisEquipment is an error yes but a non harmful one. ValheimLib on its own does nothing if its not installed with Lead

**Comment by Ramshackles** [comment]
Yeah I can see it actually works when entering the game, it's just the character screen display the character naked apparantly.

**Comment by joranbeasley** [comment]
fwiw when i get that weird naked display its because some mod has bundled in bepinex that is out of date
