### ISSUE TITLE
How To Use This?

### ISSUE THREAD

**Issue by Junrall** [xiaoxiao921/Lead#4]
Not a bug... but still might fall under "Issues"?

Sorry to post this here. The Thunderstore does not offer a way to contact mod authors.

I can't seem to figure out how to use this mod! Could you add some instructions to the mod's description?

Thanks!

~June~

**Comment by xiaoxiao921** [comment]
the readme contains everything needed, from how to craft the item and how to install it correctly, if you feel like something missing make a new issue please
